spring:
  resources:
    static-locations: classpath:/static,classpath:/public,classpath:/resources,classpath:/META-INF/resources,file:/Users/sobird/www
  mvc:
    view:
      prefix: html/
      suffix: .html